version: '3.8'

services:
  app:
    build: .
    container_name: wallet-connect-auth-app
    ports:
      - "3000:3000"  # Ваше приложение всё ещё будет работать на 3000 порту в контейнере
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    restart: unless-stopped

